In [3]:
import numpy as np

a = np.array([1,2,3])  
print(a)

[1 2 3]


In [4]:
# 生成1*5的 0 矩阵,一般用来初始化数据
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [5]:
# 生成 单位矩阵
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [6]:
student = np.dtype([('name','S20'), ('age', 'i1'), ('marks', 'f4')]) 
print(student)

[('name', 'S20'), ('age', 'i1'), ('marks', '<f4')]


In [7]:
a = np.array([[1,  2],  [3,  4]]) 
a

array([[1, 2],
       [3, 4]])

In [8]:
np.array([1,  2,  3,4,5], ndmin = 3)  

array([[[1, 2, 3, 4, 5]]])