In [2]:
import numpy as np

In [11]:
#生成3行5列的数组
a = np.arange(15).reshape(3, 5)
## 这个数组需要几个数字才能地位一个元素
print(a.shape)
## 这个数组需要几个数字才能地位一个元素,这个值就是a.shape 元素个数
print(a.dtype)
print(a.ndim)
# 元素占用的空间，这里是4byte，int类型
print(a.itemsize)
print(a.size)
a

(3, 5)
int32
2
4
15


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [12]:
b = np.array([(1.5,2,3), (4,5,6)])
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [15]:
# 创建3行4列的0数组
z = np.zeros((3,4))
z

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [16]:
# 列表长度为2
# 列表元素为3行 4列的数组
one = np.ones( (2,3,4), dtype=np.int16 )   
one

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [20]:
# arrage(start,end,step)
# 开始，结束，步长,不包含结尾元素
r = np.arange( 10, 30, 5)
r

array([10, 15, 20, 25])

In [21]:
# linspace(start,end,count)
# 从start-end 去count个元素
l = np.linspace( 0, 2, 9 )
l

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])